
services:
  redis:
    # image: 'redislabs/redismod'
    image: 'redis:7.4.0-alpine'
    # ports:
    #   - '6379:6379'

  web1:
    restart: on-failure
    build:
      context: ./web
      target: dev
    volumes:
      - ./web/src:/usr/src/app/src
    hostname: web1
    # ports:
    #   - '81:3000'
    depends_on:
      - redis
      
  nginx:
    build: ./nginx
    secrets:
       - nginx_ssl_crt
       - ngingx_ssl_key
    ports:
    - '443:443'
    depends_on:
    - web1

secrets:
  nginx_ssl_crt:
    file: ./nginx/crt/kwai.chinawarthog.com_bundle.crt
  ngingx_ssl_key:
    file: ./nginx/crt/kwai.chinawarthog.com.key